### ISSUE TITLE
Using wrong python

### ISSUE THREAD

**Issue by danielgordon10** [peterdemin/pip-compile-multi#233]
On pip-compile-multi==2.2.2 when I run `pip-compile-multi` I get this error. The issue does not seem to be present on 2.2.1

I believe the issue is in part that `/usr/bin/python` points to `python2.7` whereas `pip-compille-multi` is installed for `python3.6`. If I change the symlink for `/usr/bin/python` to `python3.6` the issue goes away.
```
Exit code: 1

/usr/bin/python: No module named piptools

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pipcompilemulti/cli_v1.py", line 26, in cli
    recompile()
  File "/usr/local/lib/python3.6/dist-packages/pipcompilemulti/actions.py", line 30, in recompile
    compile_topologically(env_confs, deduplicator)
  File "/usr/local/lib/python3.6/dist-packages/pipcompilemulti/actions.py", line 39, in compile_topologically
    if env.maybe_create_lockfile():
  File "/usr/local/lib/python3.6/dist-packages/pipcompilemulti/environment.py", line 50, in maybe_create_lockfile
    self.create_lockfile()
  File "/usr/local/lib/python3.6/dist-packages/pipcompilemulti/environment.py", line 81, in create_lockfile
    raise RuntimeError("Failed to pip-compile {0}".format(self.infile))
```

**Comment by peterdemin** [comment]
Interesting, I changed it to use `python -m piptools compile` exactly to make it more robust to environment setup.
Are you using virtualenv? Looks like you install pip-compile-multi system-wide. Is it inside of Docker?

**Comment by peterdemin** [comment]
Please upgrade to 2.3.1

**Comment by danielgordon10** [comment]
It is inside a docker. I will try 2.3.1 and see if the error persists.
