### ISSUE TITLE
Requirements with date versions (e.g. `2022.02.0`) can lead to error " was resolved to different versions in different environments"

### ISSUE THREAD

**Issue by MaxWinterstein** [peterdemin/pip-compile-multi#304]
I would propose that `pip-compile-multi` normalizes date versioned packages. In my case `fsspec` can be used as a good example.

Proof:

```bash
$ pip freeze
click==8.0.4
pep517==0.12.0
pip-compile-multi==2.4.3
pip-tools==6.5.1
tomli==2.0.1
toposort==1.7
```

```bash
$ cat base.in 
gcsfs
```

```bash
$ cat dev.in
-r base.in
dask[distributed]
```

```bash
pip-compile-multi -d .
Locking base.in to base.txt. References: []
Locking dev.in to dev.txt. References: ['base.in']
Package fsspec was resolved to different versions in different environments: 2022.2.0 and 2022.02.0
Traceback (most recent call last):
  File "/Users/winterstein/tmp/pip-compile-multi/lib/python3.10/site-packages/pipcompilemulti/cli_v1.py", line 26, in cli
    recompile()
  File "/Users/winterstein/tmp/pip-compile-multi/lib/python3.10/site-packages/pipcompilemulti/actions.py", line 31, in recompile
    compile_topologically(env_confs, deduplicator)
  File "/Users/winterstein/tmp/pip-compile-multi/lib/python3.10/site-packages/pipcompilemulti/actions.py", line 38, in compile_topologically
    if env.maybe_create_lockfile():
  File "/Users/winterstein/tmp/pip-compile-multi/lib/python3.10/site-packages/pipcompilemulti/environment.py", line 51, in maybe_create_lockfile
    self.create_lockfile()
  File "/Users/winterstein/tmp/pip-compile-multi/lib/python3.10/site-packages/pipcompilemulti/environment.py", line 72, in create_lockfile
    self.fix_lockfile()
  File "/Users/winterstein/tmp/pip-compile-multi/lib/python3.10/site-packages/pipcompilemulti/environment.py", line 134, in fix_lockfile
    sections = [
  File "/Users/winterstein/tmp/pip-compile-multi/lib/python3.10/site-packages/pipcompilemulti/environment.py", line 135, in <listcomp>
    self.fix_pin(section)
  File "/Users/winterstein/tmp/pip-compile-multi/lib/python3.10/site-packages/pipcompilemulti/environment.py", line 211, in fix_pin
    raise RuntimeError(
RuntimeError: Please add constraints for the package version listed above
```

Sure, we now can discuss why `gcfs` [has a requirement for `fsspec==2022.02.0`](https://github.com/fsspec/gcsfs/blame/main/requirements.txt#L6), but this seems not to be forbidden by pep440 (at least as far as I see) and pretty good handled by others, as neither `pip install fsspec==2022.02.0` nor `pip-compile dev.in` fails.

`pip-compile` result of this example stripped:

```bash
fsspec==2022.2.0
    # via
    #   dask
    #   gcsfs
```

**Comment by peterdemin** [comment]
Sounds good. Looks like it's safe to trim leading zeroes.
pip-compile-multi already had some logic related to normalization, and should be simple to extend with a regex for this edge case. 
But before we do that, can you find any mention about leading zeros in the official docs?

**Comment by MaxWinterstein** [comment]
> But before we do that, can you find any mention about leading zeros in the official docs?

You mean pep docs? Not much, stumpled across this:

https://github.com/python/peps/commit/4fd0075856e3e5da2faf22575574047893d7f067

**Comment by peterdemin** [comment]
That's good enough. Would you like to open a PR?
