### ISSUE TITLE
Constraint files

### ISSUE THREAD

**Issue by Niccolum** [peterdemin/pip-compile-multi#307]
Accodring https://github.com/peterdemin/pip-compile-multi/issues/91 I create simple example, which I don't know how to solve correctly.

`base1.in`
```
s3fs==2021.8.0
```

`base2.in`
```
-r base1.in
pylint==2.12.2
```

`s3fs` has no wraps version limit. Actual now - `wrapt==1.14.0`

`pylint` has `astroid>=2.9.0,<2.10`
https://github.com/PyCQA/pylint/blob/v2.12.2/setup.cfg#L47
which has limit for wraps  `wrapt>=1.11,<1.14`
https://github.com/PyCQA/astroid/blob/maintenance/2.9.x/setup.cfg#L40

so, as result for this, we have
```
$ pip-compile-multi
Locking requirements/base1.in to requirements/base1.txt. References: []
Locking requirements/base2.in to requirements/base2.txt. References: ['requirements/base1.in']
Package wrapt was resolved to different versions in different environments: 1.13.3 and 1.14.0
Traceback (most recent call last):
  File "/home/nikolay_vidov/projects/other/test_pip_compile_multi/venv/lib/python3.8/site-packages/pipcompilemulti/cli_v1.py", line 26, in cli
    recompile()
  File "/home/nikolay_vidov/projects/other/test_pip_compile_multi/venv/lib/python3.8/site-packages/pipcompilemulti/actions.py", line 31, in recompile
    compile_topologically(env_confs, deduplicator)
  File "/home/nikolay_vidov/projects/other/test_pip_compile_multi/venv/lib/python3.8/site-packages/pipcompilemulti/actions.py", line 38, in compile_topologically
    if env.maybe_create_lockfile():
  File "/home/nikolay_vidov/projects/other/test_pip_compile_multi/venv/lib/python3.8/site-packages/pipcompilemulti/environment.py", line 51, in maybe_create_lockfile
    self.create_lockfile()
  File "/home/nikolay_vidov/projects/other/test_pip_compile_multi/venv/lib/python3.8/site-packages/pipcompilemulti/environment.py", line 72, in create_lockfile
    self.fix_lockfile()
  File "/home/nikolay_vidov/projects/other/test_pip_compile_multi/venv/lib/python3.8/site-packages/pipcompilemulti/environment.py", line 134, in fix_lockfile
    sections = [
  File "/home/nikolay_vidov/projects/other/test_pip_compile_multi/venv/lib/python3.8/site-packages/pipcompilemulti/environment.py", line 135, in <listcomp>
    self.fix_pin(section)
  File "/home/nikolay_vidov/projects/other/test_pip_compile_multi/venv/lib/python3.8/site-packages/pipcompilemulti/environment.py", line 211, in fix_pin
    raise RuntimeError(
RuntimeError: Please add constraints for the package version listed above
```

Of course, as a solution, I can create two independent `*.in` files with `-c` flag and combine it in third, like

`base1.in`
```
-c base2.in
s3fs==2021.8.0
```

`base2.in`
```
pylint==2.12.2
```

`base_result.in`
```
-r base1.in
-r base2.in
```

But how we decide, where must be -c? We can't include it both to `base1.in` and `base2.in` because of circular dependency. 
What if it changes after time?
Why `pip-compile-multi` raise error, if it see different version of one library in different files?

**Comment by peterdemin** [comment]
Can you try --autoresolve flag?

**Comment by peterdemin** [comment]
> Why pip-compile-multi raise error, if it see different version of one library in different files?

Because it assumes that all environments must be compatible with each other. If it's not the case, you can compile each independent environment separately using -n flag.

**Comment by Niccolum** [comment]
> Can you try --autoresolve flag?

$ pip-compile-multi --autoresolve
Creating a temporary file with all dependencies at requirements/base2.txt
Locking requirements/base1.in to requirements/base1.txt. References: []
Locking requirements/base2.in to requirements/base2.txt. References: ['requirements/base1.in']

OK, this solve my problem. Thanks!
