### ISSUE TITLE
ImportError: cannot import name 'BAR_TYPES' from 'pip._internal.cli.progress_bars'

### ISSUE THREAD

**Issue by mmdbalkhi** [peterdemin/pip-compile-multi#324]
In this pip commit(https://github.com/pypa/pip/commit/728e4fe7c4168f62b8f47721aa56576cce5e46fb), 'BAR_TYPES' has been removed from pip and gives an error when running a program with newer pip.

issue in pip repo: https://github.com/pypa/pip/issues/10991
error:

```
Locking requirements/docs.in to requirements/docs.txt. References: []
ERROR executing /usr/bin/python -m piptools compile --no-header --verbose --rebuild --upgrade --no-emit-index-url --output-file requirements/docs.txt requirements/docs.in
Exit code: 1
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mmdbalkhi/.local/lib/python3.10/site-packages/piptools/__main__.py", line 3, in <module>
    from piptools.scripts import compile, sync
  File "/home/mmdbalkhi/.local/lib/python3.10/site-packages/piptools/scripts/compile.py", line 21, in <module>
    from ..repositories import LocalRequirementsRepository, PyPIRepository
  File "/home/mmdbalkhi/.local/lib/python3.10/site-packages/piptools/repositories/__init__.py", line 1, in <module>
    from .local import LocalRequirementsRepository
  File "/home/mmdbalkhi/.local/lib/python3.10/site-packages/piptools/repositories/local.py", line 14, in <module>
    from .pypi import PyPIRepository
  File "/home/mmdbalkhi/.local/lib/python3.10/site-packages/piptools/repositories/pypi.py", line 22, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
ImportError: cannot import name 'BAR_TYPES' from 'pip._internal.cli.progress_bars' (/home/mmdbalkhi/.local/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py)

Traceback (most recent call last):
  File "/home/mmdbalkhi/.local/lib/python3.10/site-packages/pipcompilemulti/cli_v1.py", line 26, in cli
    recompile()
  File "/home/mmdbalkhi/.local/lib/python3.10/site-packages/pipcompilemulti/actions.py", line 31, in recompile
    compile_topologically(env_confs, deduplicator)
  File "/home/mmdbalkhi/.local/lib/python3.10/site-packages/pipcompilemulti/actions.py", line 38, in compile_topologically
    if env.maybe_create_lockfile():
  File "/home/mmdbalkhi/.local/lib/python3.10/site-packages/pipcompilemulti/environment.py", line 51, in maybe_create_lockfile
    self.create_lockfile()
  File "/home/mmdbalkhi/.local/lib/python3.10/site-packages/pipcompilemulti/environment.py", line 80, in create_lockfile
    raise RuntimeError("Failed to pip-compile {0}".format(self.infile))
RuntimeError: Failed to pip-compile requirements/docs.in
```

**Comment by peterdemin** [comment]
Whenever this happens I either upgrade pip-tools, or (if it doesn't help) downgrade pip

**Comment by mmdbalkhi** [comment]
thanks @peterdemin  A temporary solution is good, Of course, I got it wrong, I thought the problem was with this program. Sorry
