### ISSUE TITLE
Cannot compile simple requirements.in after fresh install

### ISSUE THREAD

**Issue by zuckerruebe** [peterdemin/pip-compile-multi#388]
Hi there

Just tried to compile a simple requirements in after a fresh install of `pip-compile-multi` and got the following:

```ps
PS C:\Users\damian.birchler\src\pytrnsys\fortrnsys\build> py -3.9 -m venv venv
PS C:\Users\damian.birchler\src\pytrnsys\fortrnsys\build> .\venv\Scripts\activate
(venv) PS C:\Users\damian.birchler\src\pytrnsys\fortrnsys\build> python -m pip install wheel
Collecting wheel
Installing collected packages: wheel
Successfully installed wheel-0.40.0
WARNING: You are using pip version 22.0.4; however, version 23.1 is available.
You should consider upgrading via the 'C:\Users\damian.birchler\src\pytrnsys\fortrnsys\build\venv\Scripts\python.exe -m pip install --upgrade pip' command.
(venv) PS C:\Users\damian.birchler\src\pytrnsys\fortrnsys\build> python -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\damian.birchler\src\pytrnsys\fortrnsys\build\venv\lib\site-packages (22.0.4)   
Collecting pip
  Using cached pip-23.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-23.1
(venv) PS C:\Users\damian.birchler\src\pytrnsys\fortrnsys\build> python -m pip install pip-compile-multi
Collecting pip-compile-multi
  Using cached pip_compile_multi-2.6.2-py2.py3-none-any.whl (41 kB)
Collecting click (from pip-compile-multi)
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting pip-tools>=6.8.0 (from pip-compile-multi)
  Using cached pip_tools-6.13.0-py3-none-any.whl (53 kB)
Collecting toposort (from pip-compile-multi)
  Using cached toposort-1.10-py3-none-any.whl (8.5 kB)
Collecting build (from pip-tools>=6.8.0->pip-compile-multi)
Requirement already satisfied: pip>=22.2 in c:\users\damian.birchler\src\pytrnsys\fortrnsys\build\venv\lib\site-packages (from pip-tools>=6.8.0->pip-compile-multi) (23.1)
Requirement already satisfied: setuptools in c:\users\damian.birchler\src\pytrnsys\fortrnsys\build\venv\lib\site-packages (from pip-tools>=6.8.0->pip-compile-multi) (58.1.0)
Requirement already satisfied: wheel in c:\users\damian.birchler\src\pytrnsys\fortrnsys\build\venv\lib\site-packages (from pip-tools>=6.8.0->pip-compile-multi) (0.40.0)
Collecting colorama (from click->pip-compile-multi)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting packaging>=19.0 (from build->pip-tools>=6.8.0->pip-compile-multi)
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting pyproject_hooks (from build->pip-tools>=6.8.0->pip-compile-multi)
  Using cached pyproject_hooks-1.0.0-py3-none-any.whl (9.3 kB)
Collecting tomli>=1.1.0 (from build->pip-tools>=6.8.0->pip-compile-multi)
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Installing collected packages: toposort, tomli, packaging, colorama, pyproject_hooks, click, build, pip-tools, pip-compile-multi
Successfully installed build-0.10.0 click-8.1.3 colorama-0.4.6 packaging-23.1 pip-compile-multi-2.6.2 pip-tools-6.13.0 pyproject_hooks-1.0.0 tomli-2.0.1 toposort-1.10
(venv) PS C:\Users\damian.birchler\src\pytrnsys\fortrnsys\build> pip-compile-multi -d .
Locking requirements.in to requirements.txt. References: []
ERROR executing C:\Users\damian.birchler\src\pytrnsys\fortrnsys\build\venv\Scripts\python.exe -m piptools compile --no-header 
--verbose --no-emit-index-url --resolver=legacy --emit-trusted-host --upgrade --rebuild --output-file requirements.txt requirements.in
Exit code: 2
WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
Using indexes:
  https://pypi.org/simple

                          ROUND 1
Current constraints:
  coloroma (from -r requirements.in (line 2))
  pip-compile-multi (from -r requirements.in (line 1))

Finding the best candidates:
Using legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.
Could not find a version that matches coloroma (from -r requirements.in (line 2))
No versions found

Traceback (most recent call last):
  File "C:\Users\damian.birchler\src\pytrnsys\fortrnsys\build\venv\lib\site-packages\pipcompilemulti\cli_v1.py", line 26, in cli
    recompile()
  File "C:\Users\damian.birchler\src\pytrnsys\fortrnsys\build\venv\lib\site-packages\pipcompilemulti\actions.py", line 31, in 
recompile
    compile_topologically(env_confs, deduplicator)
  File "C:\Users\damian.birchler\src\pytrnsys\fortrnsys\build\venv\lib\site-packages\pipcompilemulti\actions.py", line 38, in 
compile_topologically
    if env.maybe_create_lockfile():
  File "C:\Users\damian.birchler\src\pytrnsys\fortrnsys\build\venv\lib\site-packages\pipcompilemulti\environment.py", line 51, in maybe_create_lockfile
    self.create_lockfile()
  File "C:\Users\damian.birchler\src\pytrnsys\fortrnsys\build\venv\lib\site-packages\pipcompilemulti\environment.py", line 80, in create_lockfile
    raise RuntimeError("Failed to pip-compile {0}".format(self.infile))
RuntimeError: Failed to pip-compile requirements.in
(venv) PS C:\Users\damian.birchler\src\pytrnsys\fortrnsys\build> type .\requirements.in
pip-compile-multi
coloroma
```

Any ideas what's going oin?

Cheers,
Damian

**Comment by peterdemin** [comment]
It's colorama, not coloroma

**Comment by zuckerruebe** [comment]
Haha, I wish I could make this issue un-googleable! :D

Yes, cheers, sorry about that.
