### ISSUE TITLE
Constraints are not correctly propagated across interdependencies

### ISSUE THREAD

**Issue by dtgoitia** [peterdemin/pip-compile-multi#472]
I have 5 `.in` requirement files (A, B, C, D and E) and one `.in` constraints file (X) with the following interdependencies:

![image](https://github.com/user-attachments/assets/4781170f-7267-434e-bcdf-121627c87504)

```
B includes A
B is constrained by X
C includes A
D includes A
E includes B, C and D
```

I'm using:

  - the _includes_ term above to refer to `-r file.in`
  - and the _is constrained by_ expression to refer to `-c file.in`

I've tried to resolve the above with running `pip-compile-multi` with these flags:

```shell
pip-compile-multi --autoresolve --backtracking --strip-extras --live
pip-compile-multi --autoresolve --backtracking                --live
pip-compile-multi               --backtracking --strip-extras --live
pip-compile-multi               --backtracking                --live
```

In every case, the compilation outputs the `.txt` files for X, A, B, C and D, and when it reaches E, it fails:

```
Package foo was resolved to different versions in different environments: 1.35.7 and 1.35.55
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pipcompilemulti/cli_v1.py", line 26, in cli
    recompile()
  File "/usr/local/lib/python3.10/site-packages/pipcompilemulti/actions.py", line 31, in recompile
    compile_topologically(env_confs, deduplicator)
  File "/usr/local/lib/python3.10/site-packages/pipcompilemulti/actions.py", line 38, in compile_topologically
    if env.maybe_create_lockfile():
  File "/usr/local/lib/python3.10/site-packages/pipcompilemulti/environment.py", line 51, in maybe_create_lockfile
    self.create_lockfile()
  File "/usr/local/lib/python3.10/site-packages/pipcompilemulti/environment.py", line 72, in create_lockfile
    self.fix_lockfile()
  File "/usr/local/lib/python3.10/site-packages/pipcompilemulti/environment.py", line 134, in fix_lockfile
    sections = [
  File "/usr/local/lib/python3.10/site-packages/pipcompilemulti/environment.py", line 135, in <listcomp>
    self.fix_pin(section)
  File "/usr/local/lib/python3.10/site-packages/pipcompilemulti/environment.py", line 211, in fix_pin
    raise RuntimeError(
RuntimeError: Please add constraints for the package version listed above
```

Note that:

  - B is constrained by X, and E includes B, therefore E should inherit the constraints suffered by B

  - B inherits A, and B is constrained by X, thus A must also be constrained by X

These are the produced files and the versions of `foo`:

| `.txt` file | `foo` version | observations               |
|-------------|--------------:|----------------------------|
| X           |        1.35.7 | OK, enforces `foo==1.35.7` |
| A           |       1.35.55 | 🐛, expected 1.35.7        |
| B           |        1.35.7 | OK                         |
| C           |          -r A | 🐛, expected 1.35.7        |
| D           |          -r A | 🐛, expected 1.35.7        |
| E           |            💣 | (file never produced)      |

## Expectation

All dependencies are free to resolve to the latest compatible version, while keeping the file B constrained as per X. This implies that if A, C, D and E share any dependency that B, those shared dependency must also be constrained as per X.

**Comment by peterdemin** [comment]
Does --autoresolve work? Or should mention creation of a temporary file with all dependencies. 
What is the first line of the output?

**Comment by dtgoitia** [comment]
@peterdemin sorry for the delay in the response.

> Does --autoresolve work?

The `--autoresolve` flag did not work.

> Or should mention creation of a temporary file with all dependencies.

I'm not sure what do you mean by the above.

>  What is the first line of the output?

```
Locking requirements/common.in to requirements/common.txt. References: []
```
where `requirements/common.txt` is `A` according to the nomenclature used in my first message.

**Comment by dtgoitia** [comment]
@peterdemin I've set up [this repo](https://github.com/dtgoitia/pip-compile-multi-issue-472) to reproduce the issue. Please let me know if I can clarify anything further.

**Comment by peterdemin** [comment]
In your diagram, E is the single requirements file that references (directly or indirectly) all other files. This is needed for auto-resolve to work. Please see this feature's documentation here:
https://pip-compile-multi.readthedocs.io/en/latest/features.html#autoresolve-cross-file-conflicts

**Comment by peterdemin** [comment]
I see in the repro repo, that the constraints file has an extension `.in` which makes it an input file for locking (which it is not).
I think if you rename `mwaa-2_10_1-constraints.in` to `mwaa-2_10_1-constraints.txt` (and the `-c` reference) autoresolve will see the single head of the hierarchy and resolve cross-dependencies.

**Comment by dtgoitia** [comment]
Nice! You are right @peterdemin - if the constraints file has the `.txt` extension and the `--autoresolve` flag is used, it all works like charm. Thanks!
